language: node_js
node_js:
  - "8"
stages:
  # Running tests on all branches
  - name: test
    if: (NOT type IN (pull_request))

  # Running build in test environments without deployment
  - name: build
    if: (NOT type IN (pull_request)) OR (NOT branch = master OR branch = staging)

  # Production deployment (includes build internally)
  - name: deploy-prod
    if: (NOT type IN (pull_request)) AND (branch = master)

  # Staging/Beta deployment (includes build internally)
  - name: deploy-beta
    if: (NOT type IN (pull_request)) AND (branch = staging)
jobs:
  include:
    # Run tests with coverage
    - stage: test
      script: npm run test -- --coverage

    # Build the application
    - stage: build
      script: npm run build

    # Build and deploy to production
    - stage: deploy-prod
      script: SFTP_USER=${SFTP_USER} SFTP_PASS=${SFTP_PASS} SFTP_HOST=${SFTP_HOST} npm run deploy:prod

    # Build and deploy to beta
    - stage: deploy-beta
      script: SFTP_USER=${SFTP_USER} SFTP_PASS=${SFTP_PASS} SFTP_HOST=${SFTP_HOST} npm run deploy:beta
notifications:
  email:
    on_success: never
    on_failure: change
