language: node_js
node_js:
  - "7"
stages:
  - name: build
    if: (type IN (pull_request)) OR (NOT branch = master OR branch = staging)
  - name: deploy-prod
    if: (NOT type IN (pull_request)) AND (branch = master)
  - name: deploy-beta
    if: (NOT type IN (pull_request)) AND (branch = staging)
jobs:
  include:
    - stage: build
      script: npm run build
    - stage: deploy-prod
      script: npm run deploy-prod -- --ftp-username=${FTP_USER} --ftp-pass=${FTP_PASS}
    - stage: deploy-beta
      script: npm run deploy-beta -- --ftp-username=${FTP_USER} --ftp-pass=${FTP_PASS}
notifications:
  email:
    on_success: never
    on_failure: change
